### ISSUE TITLE
mongo optimized for this query

### ISSUE THREAD

**Issue by benjaco-edu** [cph-js284/UFOblog#8]
https://www.mongodb.com/blog/post/geospatial-performance-improvements-in-mongodb-3-2

**Comment by cph-js284** [comment]
The only reason we convert back and forth is to get a buffer around the specific point, due to the fact the st_buffer can not work with SRID 4326 (the globe), however we only we only used the buffer as a rough filtering tool to distinguish between inside and outside of the selected area.
Mysql can use its own index when using st_contains to see if a point is inside the buffer, when measuring the distance to each point, then the profile tells us that it has been going through all the rows - with the buffer, it does not.

As an aside we will note that we actually ran the code both with and without the buffering and the result was almost identical (within a 2% margin).


This issue feedback was created by Yosuke, Benjamin and Jacob.
